CREATE TABLE BITCOIN (
    CODE VARCHAR(255) PRIMARY KEY,
    SYMBOL VARCHAR(255),
    RATE VARCHAR(255),
    RATE_FLOAT FLOAT,
    UPDATED TIMESTAMP,
    UPDATED_ISO TIMESTAMP,
    UPDATED_UK TIMESTAMP,
    CREATED_BY VARCHAR(255),
    CREATED_TIME TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    UPDATED_TIME TIMESTAMP
);

CREATE TABLE BITCOIN_TRANSLATION (
    CODE VARCHAR(255),
    LANGUAGE VARCHAR(255),
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_TIME TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    UPDATED_TIME TIMESTAMP,
    PRIMARY KEY (CODE, LANGUAGE)
);

CREATE TABLE EXECUTION_LOG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLASS_NAME VARCHAR(255) NOT NULL,
    METHOD_NAME VARCHAR(255) NOT NULL,
    PARAMETERS CLOB,
    RETURN_VALUE CLOB,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    DURATION BIGINT NOT NULL
);